name: Sync and Push to Hugging Face

on:
  push: 
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  sync-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - space_name: starwars-chat
            space_title: "Ask Starwars"
            space_description: "Ask questions about starwars scripts"

          - space_name: ask-langchain
            space_title: "About LangChain"
            space_description: "Ask questions about LangChain based on its documentation"

          - space_name: rare-disease
            space_title: "Rare disease"
            space_description: "Ask questions abour rare diseases based on PMC articles"

          - space_name: IRS-chat
            space_title: "Ask IRS"
            space_description: "Ask questions about taxes based on IRS website"

          - space_name: legalaid-chat
            space_title: "Ask about LegalAid"
            space_description: "Ask questions about Legal Aid in Illinois"

          - space_name: physics-bot
            space_title: "Ask about Physics"
            space_description: "Based on notes lectures by Richard Feynman" 

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2       
          
      - name: Set up Git configuration
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git config --global credential.helper store
          echo "https://USER:${{ secrets.HF_TOKEN }}@huggingface.co" > ~/.git-credentials
          
      - name: Pull target repo, update and push back
        run: |
          git clone https://${{ secrets.HF_TOKEN }}@hf.co/spaces/vectara/${{ matrix.space_name }}.git $RUNNER_TEMP/spaces/${{ matrix.space_name }}
          rsync -av --exclude '.*' $GITHUB_WORKSPACE/ $RUNNER_TEMP/spaces/${{ matrix.space_name }}/
          cd $RUNNER_TEMP/spaces/${{ matrix.space_name }}
          sed -i 's/title: "Enter Chatbot Title"/title: ${{ matrix.space_title }}/g' README.md
          sed -i 's/short_description: "Enter Description Here"/short_description: ${{ matrix.space_description }}/g' README.md
          git add .
          git commit -m "Sync updates from source repository" || echo "No changes to commit"
          echo "pushing"
          pwd
          git push origin main
          
